from __future__ import annotations

from datetime import date

from fastapi import APIRouter, Depends, Query
from fastapi.responses import HTMLResponse
from sqlalchemy.orm import Session

from app.api.dependencies import get_db
from app.services.reporting_service import get_exposures, get_pnl, get_positions, get_risk

router = APIRouter(prefix="/dashboard", tags=["dashboard"])


@router.get("/{portfolio_id}", response_class=HTMLResponse)
def dashboard(
    portfolio_id: str,
    as_of: date = Query(...),
    start_date: date = Query(...),
    db: Session = Depends(get_db),
) -> str:
    pnl = get_pnl(db, portfolio_id=portfolio_id, start_date=start_date, end_date=as_of)
    positions = get_positions(db, portfolio_id=portfolio_id, as_of=as_of)
    exposures = get_exposures(db, portfolio_id=portfolio_id, as_of=as_of, group_by="sector")
    risk = get_risk(db, portfolio_id=portfolio_id, start_date=start_date, end_date=as_of)

    rows = "".join(
        f"<tr><td>{p['ticker']}</td><td>{p['quantity']}</td><td>{p['currency']}</td>"
        f"<td>{p['market_value_base']:.2f}</td><td>{p['unrealized_pnl_base']:.2f}</td></tr>"
        for p in positions
    )
    bars = "".join(
        f"<div class='bar-row'><span>{e['group']}</span>"
        f"<div class='bar'><i style='width:{max(e['exposure_percentage'] * 100, 1):.2f}%'></i></div>"
        f"<strong>{e['exposure_percentage'] * 100:.1f}%</strong></div>"
        for e in exposures["exposures"]
    )
    return f"""
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>{portfolio_id} Risk Dashboard</title>
  <style>
    body {{ margin: 0; font-family: Inter, Arial, sans-serif; background: #f6f7f9; color: #17202a; }}
    main {{ max-width: 1120px; margin: 0 auto; padding: 28px; }}
    header {{ display: flex; justify-content: space-between; align-items: end; gap: 20px; }}
    h1 {{ margin: 0; font-size: 28px; }}
    .subtle {{ color: #5e6b78; }}
    .grid {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin: 24px 0; }}
    .card {{ background: white; border: 1px solid #dce1e7; border-radius: 8px; padding: 16px; }}
    .metric {{ font-size: 24px; font-weight: 700; margin-top: 8px; }}
    table {{ width: 100%; border-collapse: collapse; background: white; border: 1px solid #dce1e7; }}
    th, td {{ padding: 10px 12px; border-bottom: 1px solid #edf0f3; text-align: right; }}
    th:first-child, td:first-child, th:nth-child(3), td:nth-child(3) {{ text-align: left; }}
    .split {{ display: grid; grid-template-columns: 1.2fr .8fr; gap: 16px; }}
    .bar-row {{ display: grid; grid-template-columns: 90px 1fr 56px; align-items: center; gap: 10px; margin: 12px 0; }}
    .bar {{ height: 12px; background: #e7ebef; border-radius: 999px; overflow: hidden; }}
    .bar i {{ display: block; height: 100%; background: #2f6fed; }}
  </style>
</head>
<body>
  <main>
    <header>
      <div>
        <h1>{portfolio_id} Risk Dashboard</h1>
        <div class="subtle">As of {as_of.isoformat()} · Base currency USD</div>
      </div>
      <div class="subtle">Generated by FastAPI analytics engine</div>
    </header>
    <section class="grid">
      <div class="card"><div class="subtle">Total PnL</div><div class="metric">{pnl['total_pnl']:.2f}</div></div>
      <div class="card"><div class="subtle">Realized PnL</div><div class="metric">{pnl['realized_pnl']:.2f}</div></div>
      <div class="card"><div class="subtle">Unrealized PnL</div><div class="metric">{pnl['unrealized_pnl']:.2f}</div></div>
      <div class="card"><div class="subtle">Max Drawdown</div><div class="metric">{(risk['max_drawdown'] or 0) * 100:.1f}%</div></div>
    </section>
    <section class="split">
      <div>
        <h2>Positions</h2>
        <table><thead><tr><th>Ticker</th><th>Quantity</th><th>Currency</th><th>Market Value USD</th><th>Unrealized USD</th></tr></thead><tbody>{rows}</tbody></table>
      </div>
      <div>
        <h2>Sector Exposure</h2>
        <div class="card">{bars}</div>
      </div>
    </section>
  </main>
</body>
</html>
"""

